import {StyleSheet, Dimensions} from 'react-native';
import {colors} from './colors';
import i18n from './i18n';

const {width} = Dimensions.get('window');
const CARD_MARGIN = 32;
const CARD_WIDTH = (width - CARD_MARGIN) / 2;

const textAlign = i18n.language === 'ar' ? 'right' : 'left';

const styles = StyleSheet.create({
  safe: {flex: 1, backgroundColor: colors.smokeyWhite},
  header: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.brightGrey,
  },
  headerTitle: {fontSize: 22, fontWeight: '700', color: '#222', textAlign},

  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  input: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 10,
    height: 50,
    fontSize: 14,
    flex: 1,
    marginRight: 8,
    textAlign,
    color: colors.text,
  },
  searchBtn: {
    backgroundColor: colors.white,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  searchBtnText: {
    color: colors.text,
    fontWeight: '700',
    fontSize: 16,
    textAlign,
  },

  container: {flex: 1, paddingHorizontal: 12},
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    color: colors.text,
    textAlign,
  },

  card: {
    width: CARD_WIDTH,
    backgroundColor: colors.white,
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
    paddingBottom: 8,
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  image: {width: '100%', height: 120, justifyContent: 'flex-end'},
  gradient: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  infoContainer: {padding: 10},
  title: {fontSize: 15, fontWeight: '600', color: '#111', textAlign},
  date: {fontSize: 13, color: colors.subtext, marginTop: 4, textAlign},
  venue: {fontSize: 12, color: colors.subtext, marginTop: 2, textAlign},

  loader: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  empty: {
    textAlign: 'center',
    marginTop: 20,
    fontSize: 16,
    color: colors.subtext,
  },
  favoritesContainer: {
    flex: 1,
    backgroundColor: colors.smokeyWhite,
  },
  favoriteIcon: {
    position: 'absolute',
    top: 8,
    right: 8,
    borderRadius: 20,
    padding: 4,
  },
  emptyText: {
    textAlign: 'center',
    paddingVertical: 10,
    fontSize: 16,
    color: '#666',
  },
  content: {
    padding: 12,
  },
  flatListBottom: {
    paddingBottom: 100,
  },
  flatListColumnWrapper: {
    justifyContent: 'space-between',
    gap: 4,
  },
  loadingText: {marginTop: 10, color: colors.text},

  eventDetailsContainer: {
    flex: 1,
    backgroundColor: colors.smokeyWhite,
    paddingBottom: 100,
  },
  imageContainer: {position: 'relative'},
  heroImage: {width: '100%', height: 220},
  imageOverlay: {...StyleSheet.absoluteFillObject},
  eventDetailsCard: {
    marginTop: -40,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 12,
    shadowColor: colors.black,
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 30,
  },
  eventDetailsTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
    color: colors.text,
    textAlign,
  },
  section: {marginTop: 14},
  eventDetailsSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 6,
    textAlign,
    color: colors.text,
  },
  sectionText: {fontSize: 14, color: colors.subtext, lineHeight: 20, textAlign},
  linkText: {color: colors.primary, marginTop: 4, fontSize: 14, textAlign},
  performingRow: {flexDirection: 'row', marginTop: 8},
  performer: {marginRight: 16, width: 80},
  performerImg: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.brightGrey,
  },
  performerName: {
    marginTop: 6,
    fontSize: 13,
    color: colors.grey,
    textAlign,
  },
  seatmap: {width: '100%', height: 160, marginTop: 10, borderRadius: 8},
  ticketButton: {
    backgroundColor: colors.primary,
    marginTop: 20,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 3,
  },
  ticketText: {fontSize: 18, fontWeight: '600', color: colors.white, textAlign},
  row: {flexDirection: 'row', alignItems: 'center', marginBottom: 6},
  metaText: {fontSize: 14, color: colors.subtext, marginLeft: 6, textAlign},
  toggleFavorite: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 6,
  },
  favoritesFlatListColumnWrapper: {justifyContent: 'space-between'},
  favoritesFlatListContentContainer: {padding: 10},
  profileCard: {
    backgroundColor: colors.white,
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: colors.black,
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  profileContainer: {
    backgroundColor: colors.lightGreishBlue,
    paddingBottom: 20,
    flex: 1,
  },
  profileHeader: {
    alignItems: 'center',
    paddingVertical: 60,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 20,
    elevation: 4,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 3,
    borderColor: colors.white,
    marginBottom: 10,
  },
  name: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.white,
    textAlign,
  },
  email: {
    fontSize: 14,
    color: colors.brightGrey,
    marginTop: 4,
    textAlign,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: colors.grey,
    textAlign,
  },
  about: {
    fontSize: 14,
    color: colors.subtext,
    lineHeight: 20,
    textAlign,
  },
  actionList: {
    backgroundColor: colors.white,
    marginHorizontal: 20,
    borderRadius: 15,
    paddingVertical: 5,
    shadowColor: colors.black,
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.brightGrey,
  },
  actionText: {
    fontSize: 16,
    marginLeft: 15,
    color: colors.grey,
    flex: 1,
    textAlign,
  },
  arrow: {
    marginLeft: 'auto',
  },
  actionTextLogout: {
    color: colors.tomatoRed,
  },
  ticketImage: {width: '100%', height: 160, marginTop: 10, borderRadius: 8},
  snackbar: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    zIndex: 999,
    elevation: 5,
  },
  snackbarText: {
    color: colors.white,
    fontSize: 14,
  },
  eventCardImage: {borderTopLeftRadius: 14, borderTopRightRadius: 14},

  authContainer: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  icon: {width: 80, height: 80, marginBottom: 20},
  authTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 20,
    textAlign,
    color: colors.text,
  },
  authInput: {
    width: '80%',
    borderWidth: 1,
    borderColor: colors.lightGray,
    padding: 10,
    marginBottom: 12,
    borderRadius: 8,
    backgroundColor: colors.white,
    color: colors.text,
    textAlign,
  },
  authSignupButton: {
    width: '80%',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  authSignupButtonDisabled: {
    backgroundColor: colors.lightGray,
  },
  authSignupButtonEnabled: {
    backgroundColor: colors.primary,
  },
  authSignupButtonText: {color: colors.white, fontWeight: '700'},
  authLoginText: {color: colors.primary, marginTop: 10, textAlign},
  authIcon: {marginBottom: 20},
  authLogo: {width: 100, height: 100},
  loaderContainer: {flex: 1, justifyContent: 'center', alignItems: 'center'},

  emptyFavoritesContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: colors.white,
  },
  emptyEmoji: {
    fontSize: 50,
  },
  emptyHeader: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  exploreButton: {
    backgroundColor: colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  exploreButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default styles;
